from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from app.config import CANDIDATE_ENTITIES_JSON, CANDIDATE_RELATIONS_JSON


def _now() -> str:
    return datetime.now(UTC).isoformat()


_DEMO_ENTITY_TEMPLATES: list[dict[str, Any]] = [
    {
        "id": "CUST-CRO-001",
        "type": "CustomerSegment",
        "label": "Preclinical CROs",
        "description": "Contract research organizations running repeated preclinical study workflows.",
        "source_document_id": "sample-pitch",
        "source_file": "sample_data/pitch_deck_text.md",
        "source_snippet": "Preclinical CROs urgently need metadata interoperability to reduce duplicated data entry.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["customer"],
    },
    {
        "id": "PROB-META-001",
        "type": "Problem",
        "label": "Fragmented preclinical metadata",
        "description": "Metadata are lost across LIMS, spreadsheets, ELNs, imaging tools, and reporting templates.",
        "source_document_id": "sample-interview-cro",
        "source_file": "sample_data/customer_interview_cro_01.docx",
        "source_snippet": "The team loses metadata between the LIMS, spreadsheets, and study reports.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["metadata", "interoperability"],
    },
    {
        "id": "FEAT-MAP-001",
        "type": "ProductFeature",
        "label": "Metadata mapping layer",
        "description": "A lightweight metadata layer that maps experimental context across tools.",
        "source_document_id": "sample-business-plan",
        "source_file": "sample_data/business_plan.md",
        "source_snippet": "The first wedge is a lightweight metadata layer that maps experimental context.",
        "confidence": "medium",
        "validation_status": "pending",
        "tags": ["product"],
    },
    {
        "id": "ASSUMP-WTP-001",
        "type": "Assumption",
        "label": "CROs will pay for metadata interoperability",
        "description": "CROs will pay for integration if it reduces duplicated data entry.",
        "source_document_id": "sample-business-plan",
        "source_file": "sample_data/business_plan.md",
        "source_snippet": "CROs will pay for integration if it reduces duplicated data entry.",
        "confidence": "medium",
        "validation_status": "pending",
        "tags": ["pricing", "gtm"],
    },
    {
        "id": "ASSUMP-AI-001",
        "type": "Assumption",
        "label": "Pharma needs metadata for AI-readiness",
        "description": "Pharma translational teams will sponsor pilots when metadata quality affects AI readiness.",
        "source_document_id": "sample-pitch",
        "source_file": "sample_data/pitch_deck_text.md",
        "source_snippet": "Pharma translational teams need traceable metadata for AI-ready research datasets.",
        "confidence": "medium",
        "validation_status": "pending",
        "tags": ["pharma", "ai-readiness"],
    },
    {
        "id": "EVID-CRO-001",
        "type": "Evidence",
        "label": "CRO interview reports metadata loss",
        "description": "A CRO operations lead described metadata loss across tools.",
        "source_document_id": "sample-interview-cro",
        "source_file": "sample_data/customer_interview_cro_01.docx",
        "source_snippet": "The team loses metadata between the LIMS, spreadsheets, and study reports.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["interview"],
    },
    {
        "id": "EVID-PHARMA-001",
        "type": "Evidence",
        "label": "Pharma stakeholder asks for provenance",
        "description": "A pharma stakeholder asked for better provenance before AI-readiness pilots.",
        "source_document_id": "sample-pitch",
        "source_file": "sample_data/pitch_deck_text.md",
        "source_snippet": "A pharma stakeholder asked for better provenance before approving AI-readiness pilots.",
        "confidence": "medium",
        "validation_status": "pending",
        "tags": ["stakeholder"],
    },
    {
        "id": "RISK-SALES-001",
        "type": "Risk",
        "label": "Long enterprise sales cycle",
        "description": "Enterprise sales cycles may delay revenue and pilots.",
        "source_document_id": "sample-pitch",
        "source_file": "sample_data/pitch_deck_text.md",
        "source_snippet": "Enterprise sales cycles may be longer than expected.",
        "confidence": "medium",
        "validation_status": "pending",
        "tags": ["sales"],
    },
    {
        "id": "RISK-INT-001",
        "type": "Risk",
        "label": "Legacy integration complexity",
        "description": "Integrations with legacy research tools may be harder than planned.",
        "source_document_id": "sample-roadmap",
        "source_file": "sample_data/technical_roadmap.md",
        "source_snippet": "Legacy system integration complexity.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["technical"],
    },
]

_DEMO_RELATION_TEMPLATES: list[dict[str, Any]] = [
    {
        "id": "REL-CRO-PROB-001",
        "subject_id": "CUST-CRO-001",
        "subject_type": "CustomerSegment",
        "predicate": "HAS_PROBLEM",
        "object_id": "PROB-META-001",
        "object_type": "Problem",
        "source_document_id": "sample-interview-cro",
        "source_file": "sample_data/customer_interview_cro_01.docx",
        "source_snippet": "The team loses metadata between the LIMS, spreadsheets, and study reports.",
        "confidence": "high",
        "validation_status": "pending",
    },
    {
        "id": "REL-FEAT-PROB-001",
        "subject_id": "FEAT-MAP-001",
        "subject_type": "ProductFeature",
        "predicate": "ADDRESSES",
        "object_id": "PROB-META-001",
        "object_type": "Problem",
        "source_document_id": "sample-business-plan",
        "source_file": "sample_data/business_plan.md",
        "source_snippet": "A lightweight metadata layer that maps experimental context across study planning.",
        "confidence": "medium",
        "validation_status": "pending",
    },
    {
        "id": "REL-ASSUMP-EVID-001",
        "subject_id": "ASSUMP-AI-001",
        "subject_type": "Assumption",
        "predicate": "SUPPORTED_BY",
        "object_id": "EVID-PHARMA-001",
        "object_type": "Evidence",
        "source_document_id": "sample-pitch",
        "source_file": "sample_data/pitch_deck_text.md",
        "source_snippet": "A pharma stakeholder asked for better provenance before approving AI-readiness pilots.",
        "confidence": "medium",
        "validation_status": "pending",
    },
]


_TRIALMESH_ENTITY_TEMPLATES: list[dict[str, Any]] = [
    {
        "id": "TM-STARTUP-001",
        "type": "Startup",
        "label": "TrialMesh",
        "description": "A local-first evidence orchestration platform for clinical trial startup teams.",
        "source_document_id": "trialmesh-company-profile",
        "source_file": "sample_data/trialmesh/00_overview/company_profile.md",
        "source_snippet": "TrialMesh sells a local-first evidence orchestration platform for clinical trial startup teams.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["trialmesh", "startup"],
    },
    {
        "id": "TM-CUST-SPONSOR-001",
        "type": "CustomerSegment",
        "label": "Clinical trial sponsors",
        "description": "Sponsor teams coordinating trial startup evidence, vendors, and regulatory readiness.",
        "source_document_id": "trialmesh-customer-segments",
        "source_file": "sample_data/trialmesh/01_market/customer_segments_and_problem.md",
        "source_snippet": "Sponsors and CROs need better coordination across trial startup packets, vendors, and evidence.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["customer", "sponsor"],
    },
    {
        "id": "TM-CUST-CRO-001",
        "type": "CustomerSegment",
        "label": "CRO startup operations teams",
        "description": "CRO teams managing site startup workflows, document handoffs, and operational evidence.",
        "source_document_id": "trialmesh-cro-interview",
        "source_file": "sample_data/trialmesh/01_market/interviews/cro_program_director_interview.txt",
        "source_snippet": "CRO program directors described startup delays caused by handoffs and version confusion.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["customer", "cro"],
    },
    {
        "id": "TM-PROB-STARTUP-DELAY-001",
        "type": "Problem",
        "label": "Site startup delays",
        "description": "Clinical trial startup teams lose time reconciling packets, versions, vendor handoffs, and approvals.",
        "source_document_id": "trialmesh-company-profile",
        "source_file": "sample_data/trialmesh/00_overview/company_profile.md",
        "source_snippet": "The product helps sponsors and CROs reduce trial startup delays.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["problem", "startup"],
    },
    {
        "id": "TM-PROB-VERSION-CONFUSION-001",
        "type": "Problem",
        "label": "Document version confusion",
        "description": "Teams struggle to know which protocol packet, amendment, or evidence artifact is authoritative.",
        "source_document_id": "trialmesh-site-ops-interview",
        "source_file": "sample_data/trialmesh/01_market/interviews/site_ops_director_interview.txt",
        "source_snippet": "Customer interviews show urgency around protocol amendments, document version confusion, and vendor handoffs.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["problem", "documents"],
    },
    {
        "id": "TM-FEAT-EVIDENCE-GRAPH-001",
        "type": "ProductFeature",
        "label": "Validated evidence graph",
        "description": "A knowledge graph that links claims, documents, risks, requirements, and operating evidence.",
        "source_document_id": "trialmesh-product-requirements",
        "source_file": "sample_data/trialmesh/02_product/product_requirements.md",
        "source_snippet": "Operational evidence is turned into a validated knowledge graph.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["product", "graph"],
    },
    {
        "id": "TM-ASSUMP-CYCLE-TIME-001",
        "type": "Assumption",
        "label": "TrialMesh can reduce site startup cycle time by 21 percent",
        "description": "TrialMesh claims its workflow can reduce site startup cycle time by 21 percent.",
        "source_document_id": "trialmesh-pilot-results",
        "source_file": "sample_data/trialmesh/03_evidence/pilot_results.md",
        "source_snippet": "The startup claims it can reduce site startup cycle time by 21 percent.",
        "confidence": "medium",
        "validation_status": "pending",
        "tags": ["assumption", "kpi"],
    },
    {
        "id": "TM-EVID-PILOT-001",
        "type": "Evidence",
        "label": "Pilot results report startup cycle-time reduction",
        "description": "Pilot evidence reports a reduction in site startup cycle time.",
        "source_document_id": "trialmesh-pilot-results",
        "source_file": "sample_data/trialmesh/03_evidence/pilot_results.md",
        "source_snippet": "Pilot results are used as evidence for the 21 percent cycle-time reduction claim.",
        "confidence": "medium",
        "validation_status": "pending",
        "tags": ["evidence", "pilot"],
    },
    {
        "id": "TM-RISK-COMPLIANCE-001",
        "type": "Risk",
        "label": "HIPAA and 21 CFR Part 11 compliance risk",
        "description": "Clinical trial workflows create compliance risk around HIPAA, auditability, signatures, and regulated records.",
        "source_document_id": "trialmesh-compliance-gap",
        "source_file": "sample_data/trialmesh/05_regulatory/compliance_gap_assessment.md",
        "source_snippet": "Regulatory notes surface HIPAA, 21 CFR Part 11, and ICH E6 concerns.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["risk", "regulatory"],
    },
    {
        "id": "TM-DEP-M365-001",
        "type": "TechnicalDependency",
        "label": "Microsoft 365 integration",
        "description": "TrialMesh depends on Microsoft 365 integration for customer document and workflow environments.",
        "source_document_id": "trialmesh-product-requirements",
        "source_file": "sample_data/trialmesh/02_product/product_requirements.md",
        "source_snippet": "Product docs reveal dependencies on Microsoft 365, SSO, audit logs, and redaction workflows.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["dependency", "integration"],
    },
    {
        "id": "TM-MILESTONE-PILOTS-001",
        "type": "Milestone",
        "label": "Secure three lighthouse pilots",
        "description": "TrialMesh depends on landing three lighthouse pilots before an enterprise conversion.",
        "source_document_id": "trialmesh-financial-model",
        "source_file": "sample_data/trialmesh/04_finance/financial_model.csv",
        "source_snippet": "Finance assumptions reveal dependency on 3 lighthouse pilots and one enterprise conversion.",
        "confidence": "medium",
        "validation_status": "pending",
        "tags": ["milestone", "finance"],
    },
    {
        "id": "TM-INVESTOR-PIPELINE-001",
        "type": "Investor",
        "label": "Healthcare workflow investors",
        "description": "Investors in the TrialMesh pipeline focused on healthcare workflow, evidence, and regulated SaaS.",
        "source_document_id": "trialmesh-investor-pipeline",
        "source_file": "sample_data/trialmesh/06_partnerships/investor_pipeline.csv",
        "source_snippet": "Investor pipeline includes funds evaluating healthcare workflow and evidence orchestration themes.",
        "confidence": "medium",
        "validation_status": "pending",
        "tags": ["investor"],
    },
]

_TRIALMESH_RELATION_TEMPLATES: list[dict[str, Any]] = [
    {
        "id": "TM-REL-STARTUP-SPONSOR-001",
        "subject_id": "TM-STARTUP-001",
        "subject_type": "Startup",
        "predicate": "TARGETS",
        "object_id": "TM-CUST-SPONSOR-001",
        "object_type": "CustomerSegment",
        "source_document_id": "trialmesh-customer-segments",
        "source_file": "sample_data/trialmesh/01_market/customer_segments_and_problem.md",
        "source_snippet": "Sponsors and CROs need better coordination across trial startup packets, vendors, and evidence.",
        "confidence": "high",
        "validation_status": "pending",
    },
    {
        "id": "TM-REL-CRO-PROBLEM-001",
        "subject_id": "TM-CUST-CRO-001",
        "subject_type": "CustomerSegment",
        "predicate": "HAS_PROBLEM",
        "object_id": "TM-PROB-VERSION-CONFUSION-001",
        "object_type": "Problem",
        "source_document_id": "trialmesh-cro-interview",
        "source_file": "sample_data/trialmesh/01_market/interviews/cro_program_director_interview.txt",
        "source_snippet": "CRO program directors described startup delays caused by handoffs and version confusion.",
        "confidence": "high",
        "validation_status": "pending",
    },
    {
        "id": "TM-REL-FEATURE-PROBLEM-001",
        "subject_id": "TM-FEAT-EVIDENCE-GRAPH-001",
        "subject_type": "ProductFeature",
        "predicate": "ADDRESSES",
        "object_id": "TM-PROB-STARTUP-DELAY-001",
        "object_type": "Problem",
        "source_document_id": "trialmesh-product-requirements",
        "source_file": "sample_data/trialmesh/02_product/product_requirements.md",
        "source_snippet": "Operational evidence is turned into a validated knowledge graph to reduce startup delays.",
        "confidence": "medium",
        "validation_status": "pending",
    },
    {
        "id": "TM-REL-ASSUMP-EVIDENCE-001",
        "subject_id": "TM-ASSUMP-CYCLE-TIME-001",
        "subject_type": "Assumption",
        "predicate": "SUPPORTED_BY",
        "object_id": "TM-EVID-PILOT-001",
        "object_type": "Evidence",
        "source_document_id": "trialmesh-pilot-results",
        "source_file": "sample_data/trialmesh/03_evidence/pilot_results.md",
        "source_snippet": "Pilot results are used as evidence for the 21 percent cycle-time reduction claim.",
        "confidence": "medium",
        "validation_status": "pending",
    },
    {
        "id": "TM-REL-RISK-MILESTONE-001",
        "subject_id": "TM-RISK-COMPLIANCE-001",
        "subject_type": "Risk",
        "predicate": "THREATENS",
        "object_id": "TM-MILESTONE-PILOTS-001",
        "object_type": "Milestone",
        "source_document_id": "trialmesh-compliance-gap",
        "source_file": "sample_data/trialmesh/05_regulatory/compliance_gap_assessment.md",
        "source_snippet": "Regulatory concerns could slow pilots and enterprise conversion.",
        "confidence": "medium",
        "validation_status": "pending",
    },
]


def _write_candidates(
    entities: list[dict[str, Any]],
    relations: list[dict[str, Any]],
    *,
    overwrite: bool,
) -> tuple[Path, Path]:
    CANDIDATE_ENTITIES_JSON.parent.mkdir(parents=True, exist_ok=True)
    CANDIDATE_RELATIONS_JSON.parent.mkdir(parents=True, exist_ok=True)
    now = _now()
    if overwrite or not CANDIDATE_ENTITIES_JSON.exists():
        entities_with_timestamps = [{**e, "created_at": now, "updated_at": now} for e in entities]
        CANDIDATE_ENTITIES_JSON.write_text(
            json.dumps(entities_with_timestamps, indent=2) + "\n",
            encoding="utf-8",
        )
    if overwrite or not CANDIDATE_RELATIONS_JSON.exists():
        relations_with_timestamps = [{**r, "created_at": now, "updated_at": now} for r in relations]
        CANDIDATE_RELATIONS_JSON.write_text(
            json.dumps(relations_with_timestamps, indent=2) + "\n",
            encoding="utf-8",
        )
    return CANDIDATE_ENTITIES_JSON, CANDIDATE_RELATIONS_JSON


def seed_demo_candidates(overwrite: bool = False) -> tuple[Path, Path]:
    return _write_candidates(_DEMO_ENTITY_TEMPLATES, _DEMO_RELATION_TEMPLATES, overwrite=overwrite)


def seed_trialmesh_candidates(overwrite: bool = False) -> tuple[Path, Path]:
    return _write_candidates(_TRIALMESH_ENTITY_TEMPLATES, _TRIALMESH_RELATION_TEMPLATES, overwrite=overwrite)


_METADATAPP_ENTITY_TEMPLATES: list[dict[str, Any]] = [
    # --- Core project ---
    {
        "id": "MAPP-PROJ-001",
        "type": "StartupProject",
        "label": "Metadatapp",
        "description": "FAIR-by-design metadata platform for preclinical animal research. Helps teams capture, validate, connect, and reuse experimental metadata.",
        "source_document_id": "KB-000",
        "source_file": "sample_data/metadatapp_kb/00_overview/README.md",
        "source_snippet": "FAIR-by-design metadata platform for preclinical animal research.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["startup", "platform"],
    },
    # --- Use cases ---
    {
        "id": "MAPP-UC-001",
        "type": "UseCase",
        "label": "Home Cage Monitoring",
        "description": "Automated longitudinal monitoring in animal home cages. The initial product wedge requiring structured protocol context metadata.",
        "source_document_id": "PRD-003",
        "source_file": "sample_data/metadatapp_kb/02_product/prd-003_mvp_scope.md",
        "source_snippet": "The initial wedge is Home Cage Monitoring data from ARRIVE Export.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["use-case", "hcm", "wedge"],
    },
    {
        "id": "MAPP-UC-002",
        "type": "UseCase",
        "label": "VCG Readiness Review",
        "description": "Assessing metadata readiness for historical control group comparability review.",
        "source_document_id": "PRD-008",
        "source_file": "sample_data/metadatapp_kb/02_product/prd-008_vcg_readiness_module.md",
        "source_snippet": "The VCG Readiness Module assesses metadata completeness for historical control review.",
        "confidence": "medium",
        "validation_status": "pending",
        "tags": ["use-case", "vcg"],
    },
    # --- Concepts ---
    {
        "id": "MAPP-CONC-001",
        "type": "Concept",
        "label": "FAIRRR",
        "description": "FAIR for Animals and Responsible Research — extending FAIR data principles to preclinical animal experiment contexts.",
        "source_document_id": "STR-001",
        "source_file": "sample_data/metadatapp_kb/01_strategy/str-001_vision_and_mission.md",
        "source_snippet": "Metadatapp supports FAIRRR: FAIR for Animals and responsible research.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["concept", "fair"],
    },
    {
        "id": "MAPP-CONC-002",
        "type": "Concept",
        "label": "Human Review",
        "description": "Mandatory human oversight required before any AI-suggested metadata mapping is accepted into validated knowledge.",
        "source_document_id": "PRD-007",
        "source_file": "sample_data/metadatapp_kb/02_product/prd-007_ai_assistant_boundaries.md",
        "source_snippet": "AI suggestions require human review before acceptance.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["concept", "ai-safety"],
    },
    {
        "id": "MAPP-CONC-003",
        "type": "Concept",
        "label": "Community Adoption",
        "description": "Building a user base via open-source release to drive trust, contributions, and downstream enterprise sales.",
        "source_document_id": "STR-005",
        "source_file": "sample_data/metadatapp_kb/01_strategy/str-005_business_model.md",
        "source_snippet": "Open-source core can build trust and academic adoption.",
        "confidence": "medium",
        "validation_status": "pending",
        "tags": ["concept", "growth"],
    },
    # --- Standards ---
    {
        "id": "MAPP-STAND-001",
        "type": "Standard",
        "label": "FAIR Principles",
        "description": "Findable, Accessible, Interoperable, Reusable principles for research data management.",
        "source_document_id": "KB-000",
        "source_file": "sample_data/metadatapp_kb/00_overview/entity_registry.json",
        "source_snippet": "FAIR: Findable, Accessible, Interoperable, Reusable principles.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["standard", "fair"],
    },
    {
        "id": "MAPP-STAND-002",
        "type": "Standard",
        "label": "ARRIVE Guidelines",
        "description": "Animal Research Reporting of In Vivo Experiments. A reporting checklist standard for preclinical publications.",
        "source_document_id": "PRD-009",
        "source_file": "sample_data/metadatapp_kb/02_product/prd-009_arrive_export.md",
        "source_snippet": "ARRIVE reporting checklist draft from structured metadata.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["standard", "reporting"],
    },
    {
        "id": "MAPP-STAND-003",
        "type": "Standard",
        "label": "RO-Crate",
        "description": "Research Object packaging format for bundling datasets with metadata into portable, citable archives.",
        "source_document_id": "PRD-006",
        "source_file": "sample_data/metadatapp_kb/02_product/prd-006_import_export_specification.md",
        "source_snippet": "RO-Crate research object package export.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["standard", "export"],
    },
    {
        "id": "MAPP-STAND-004",
        "type": "Standard",
        "label": "JSON-LD",
        "description": "JSON serialization for linked data, providing a lightweight mechanism for attaching semantic context.",
        "source_document_id": "TECH-004",
        "source_file": "sample_data/metadatapp_kb/03_technical/tech-004_json_ld_context_strategy.md",
        "source_snippet": "JSON-LD export format for linked data.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["standard", "linked-data"],
    },
    # --- Export formats ---
    {
        "id": "MAPP-EXP-001",
        "type": "ExportFormat",
        "label": "JSON-LD Export",
        "description": "Linked data export in JSON-LD format, mapping experiment metadata to stable ontology terms.",
        "source_document_id": "PRD-006",
        "source_file": "sample_data/metadatapp_kb/02_product/prd-006_import_export_specification.md",
        "source_snippet": "JSON-LD export maps local labels to stable ontology concepts.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["export"],
    },
    {
        "id": "MAPP-EXP-002",
        "type": "ExportFormat",
        "label": "RO-Crate Export",
        "description": "Research object package export bundling data, metadata, and provenance into a self-describing archive.",
        "source_document_id": "PRD-006",
        "source_file": "sample_data/metadatapp_kb/02_product/prd-006_import_export_specification.md",
        "source_snippet": "RO-Crate export packages research objects with provenance.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["export"],
    },
    {
        "id": "MAPP-EXP-003",
        "type": "ExportFormat",
        "label": "ARRIVE Export",
        "description": "Auto-generated ARRIVE reporting checklist draft populated from structured experiment metadata.",
        "source_document_id": "PRD-009",
        "source_file": "sample_data/metadatapp_kb/02_product/prd-009_arrive_export.md",
        "source_snippet": "Reporting checklist draft auto-generated from structured metadata.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["export", "reporting"],
    },
    # --- Product modules ---
    {
        "id": "MAPP-MOD-001",
        "type": "ProductModule",
        "label": "Validation Report",
        "description": "Module that checks metadata completeness, flags missing fields, and produces a structured validation report.",
        "source_document_id": "PRD-001",
        "source_file": "sample_data/metadatapp_kb/02_product/prd-001_product_requirements_document.md",
        "source_snippet": "Validation Report lists missing or inconsistent metadata.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["module", "validation"],
    },
    {
        "id": "MAPP-MOD-002",
        "type": "ProductModule",
        "label": "VCG Readiness Module",
        "description": "Assesses metadata completeness for historical control group comparability — a key pharma readiness check.",
        "source_document_id": "PRD-008",
        "source_file": "sample_data/metadatapp_kb/02_product/prd-008_vcg_readiness_module.md",
        "source_snippet": "VCG Readiness Module assesses metadata readiness for historical control review.",
        "confidence": "medium",
        "validation_status": "pending",
        "tags": ["module", "vcg"],
    },
    {
        "id": "MAPP-MOD-003",
        "type": "ProductModule",
        "label": "Experiment Registry",
        "description": "Central registry of all experiment records, linking protocols, cohorts, procedures, and endpoints.",
        "source_document_id": "PRD-001",
        "source_file": "sample_data/metadatapp_kb/02_product/prd-001_product_requirements_document.md",
        "source_snippet": "Experiment Registry is a core module in the Metadatapp platform.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["module", "core"],
    },
    {
        "id": "MAPP-MOD-004",
        "type": "ProductModule",
        "label": "Protocol Metadata Builder",
        "description": "Guided UI for capturing structured protocol context including species, strain, cage system, endpoints, and light cycle.",
        "source_document_id": "PRD-005",
        "source_file": "sample_data/metadatapp_kb/02_product/prd-005_experiment_creation_workflow.md",
        "source_snippet": "Protocol Metadata Builder guides structured protocol context capture.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["module", "ux"],
    },
    # --- Product features ---
    {
        "id": "MAPP-FEAT-001",
        "type": "ProductFeature",
        "label": "AI Assistant",
        "description": "AI layer that suggests ontology mappings and metadata summaries. Does not validate facts; all suggestions require human review.",
        "source_document_id": "PRD-007",
        "source_file": "sample_data/metadatapp_kb/02_product/prd-007_ai_assistant_boundaries.md",
        "source_snippet": "AI Assistant suggests mappings and summaries but does not validate facts.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["feature", "ai"],
    },
    {
        "id": "MAPP-FEAT-002",
        "type": "ProductFeature",
        "label": "Knowledge Graph Layer",
        "description": "Semantic graph linking experiment entities, standards, ontology terms, and provenance to support reuse and querying.",
        "source_document_id": "KG-005",
        "source_file": "sample_data/metadatapp_kb/08_knowledge_graph/kg-005_graph_schema_notes.md",
        "source_snippet": "Knowledge Graph Layer connects experiments, standards, and ontology terms.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["feature", "graph"],
    },
    # --- Technical capabilities ---
    {
        "id": "MAPP-TECH-001",
        "type": "TechnicalCapability",
        "label": "SHACL Validation",
        "description": "Semantic validation using SHACL shape constraints to enforce metadata completeness rules on RDF graphs.",
        "source_document_id": "TECH-005",
        "source_file": "sample_data/metadatapp_kb/03_technical/tech-005_shacl_validation_strategy.md",
        "source_snippet": "SHACL validation uses shape constraints for semantic metadata validation.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["technical", "validation"],
    },
    {
        "id": "MAPP-TECH-002",
        "type": "TechnicalCapability",
        "label": "Ontology Layer",
        "description": "Maps local experiment labels to stable ontology terms. Supports JSON-LD context and SHACL shape generation.",
        "source_document_id": "TECH-006",
        "source_file": "sample_data/metadatapp_kb/03_technical/tech-006_ontology_layer.md",
        "source_snippet": "Ontology Layer maps local labels to stable concepts.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["technical", "ontology"],
    },
    {
        "id": "MAPP-TECH-003",
        "type": "TechnicalCapability",
        "label": "Connector Framework",
        "description": "Import-and-map framework for pulling metadata from external systems such as ELNs, LIMS, HCM vendors, and ORCID.",
        "source_document_id": "TECH-007",
        "source_file": "sample_data/metadatapp_kb/03_technical/tech-007_connector_architecture.md",
        "source_snippet": "Connector Framework imports and maps external system data.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["technical", "integration"],
    },
    {
        "id": "MAPP-TECH-004",
        "type": "TechnicalCapability",
        "label": "Security and RBAC",
        "description": "Role-based access control and security controls required for enterprise and multi-tenant deployments.",
        "source_document_id": "TECH-008",
        "source_file": "sample_data/metadatapp_kb/03_technical/tech-008_security_and_rbac.md",
        "source_snippet": "Security and RBAC are required for enterprise deployments.",
        "confidence": "medium",
        "validation_status": "pending",
        "tags": ["technical", "security"],
    },
    # --- Technologies (from meeting notes) ---
    {
        "id": "MAPP-TECH-005",
        "type": "Technology",
        "label": "Google Cloud Run",
        "description": "Serverless container platform used for auto-scaling Metadatapp services with idle shutdown to minimize cloud costs.",
        "source_document_id": "MTG-OCT-2025",
        "source_file": "sample_data/metadatapp_kb/00_ALL_meeting_notes.txt",
        "source_snippet": "Cloud Run auto-scaling and idle shutdown strategies reduce cloud costs.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["technology", "cloud"],
    },
    {
        "id": "MAPP-TECH-006",
        "type": "Technology",
        "label": "Terraform",
        "description": "Infrastructure-as-code tool used to provision PostgreSQL, Cloud Run services, and GCP environments for Metadatapp.",
        "source_document_id": "MTG-OCT-2025",
        "source_file": "sample_data/metadatapp_kb/00_ALL_meeting_notes.txt",
        "source_snippet": "Rakesh prepared Terraform scripts for deploying a minimal auto-scaling database.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["technology", "devops"],
    },
    {
        "id": "MAPP-TECH-007",
        "type": "Technology",
        "label": "ElabFTW",
        "description": "Open-source electronic lab notebook integrated with Metadatapp as a connected app to fetch protocol and equipment metadata.",
        "source_document_id": "MTG-OCT-2025",
        "source_file": "sample_data/metadatapp_kb/00_ALL_meeting_notes.txt",
        "source_snippet": "ElabFTW is integrated as a connector to fetch protocol and equipment data.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["technology", "eln", "connector"],
    },
    {
        "id": "MAPP-TECH-008",
        "type": "Technology",
        "label": "SoftMouse",
        "description": "Animal colony management software connected to Metadatapp for importing registered mouse cohort metadata.",
        "source_document_id": "MTG-OCT-2025",
        "source_file": "sample_data/metadatapp_kb/00_ALL_meeting_notes.txt",
        "source_snippet": "The mice are already registered in SoftMouse.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["technology", "animal-management", "connector"],
    },
    {
        "id": "MAPP-TECH-009",
        "type": "Technology",
        "label": "ORCID",
        "description": "Open Researcher and Contributor ID API used to enrich Metadatapp user profiles with verified researcher identifiers.",
        "source_document_id": "MTG-OCT-2025",
        "source_file": "sample_data/metadatapp_kb/00_ALL_meeting_notes.txt",
        "source_snippet": "ORCID API used to fetch user data without full OAuth login flow.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["technology", "identity"],
    },
    {
        "id": "MAPP-TECH-010",
        "type": "Technology",
        "label": "Fair3R",
        "description": "FAIR data repository for sharing preclinical datasets. Metadatapp syncs experiments to Fair3R applying appropriate metadata schema and issuing DOIs.",
        "source_document_id": "MTG-OCT-2025",
        "source_file": "sample_data/metadatapp_kb/00_ALL_meeting_notes.txt",
        "source_snippet": "Synced with Fair3R repository applying FAIR metadata schema to obtain a DOI.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["technology", "repository"],
    },
    # --- People ---
    {
        "id": "MAPP-PERSON-001",
        "type": "Person",
        "label": "Damien Huzard",
        "description": "Co-founder of Metadatapp. Leading product strategy, pitch, user feedback, and Google Cloud setup.",
        "source_document_id": "MTG-OCT-2025",
        "source_file": "sample_data/metadatapp_kb/00_ALL_meeting_notes.txt",
        "source_snippet": "Damien: Follow up with user feedback on pitch website and create Google Cloud projects.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["person", "founder"],
    },
    {
        "id": "MAPP-PERSON-002",
        "type": "Person",
        "label": "Rakesh Beedasy",
        "description": "Technical co-founder or lead engineer at Metadatapp. Responsible for Terraform, Cloud Run, CI/CD, and connector development.",
        "source_document_id": "MTG-OCT-2025",
        "source_file": "sample_data/metadatapp_kb/00_ALL_meeting_notes.txt",
        "source_snippet": "Rakesh: Prepare Terraform scripts for deploying minimal auto-scaling database and metadata app.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["person", "technical"],
    },
    {
        "id": "MAPP-PERSON-003",
        "type": "Person",
        "label": "Laurent",
        "description": "Engineering advisor or contractor at Metadatapp. Leading connector refactoring and architecture decisions.",
        "source_document_id": "MTG-OCT-2025",
        "source_file": "sample_data/metadatapp_kb/00_ALL_meeting_notes.txt",
        "source_snippet": "Laurent: Refactoring archi. Connected apps architecture decisions.",
        "confidence": "medium",
        "validation_status": "pending",
        "tags": ["person", "advisor"],
    },
    # --- Decisions ---
    {
        "id": "MAPP-DEC-001",
        "type": "Decision",
        "label": "Drop Keycloak for MVP",
        "description": "Decision to remove Keycloak authentication from the MVP to reduce cloud costs and maintenance overhead. Replaced with lightweight mock auth.",
        "source_document_id": "MTG-OCT-2025",
        "source_file": "sample_data/metadatapp_kb/00_ALL_meeting_notes.txt",
        "source_snippet": "Décision: On n'utilise plus Keycloack. En premier temps on peut mettre en dur, mocker l'auth.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["decision", "authentication"],
    },
    {
        "id": "MAPP-DEC-002",
        "type": "Decision",
        "label": "Open-source core strategy",
        "description": "Decision to release the core metadata platform as open source to drive academic adoption, build trust, and create an enterprise sales funnel.",
        "source_document_id": "STR-005",
        "source_file": "sample_data/metadatapp_kb/01_strategy/str-005_business_model.md",
        "source_snippet": "Open-source core can build trust and academic adoption.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["decision", "strategy"],
    },
    {
        "id": "MAPP-DEC-003",
        "type": "Decision",
        "label": "HCM as initial product wedge",
        "description": "Strategic decision to enter the market via Home Cage Monitoring as the first use case, deferring broader preclinical platform scope.",
        "source_document_id": "STR-010",
        "source_file": "sample_data/metadatapp_kb/01_strategy/str-010_positioning_statement.md",
        "source_snippet": "Metadatapp has_initial_wedge Home Cage Monitoring.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["decision", "strategy", "wedge"],
    },
    # --- Customer segments ---
    {
        "id": "MAPP-SEG-001",
        "type": "CustomerSegment",
        "label": "Preclinical CROs",
        "description": "Contract research organizations running repeated preclinical study workflows that need metadata interoperability to reduce duplicated data entry.",
        "source_document_id": "STR-003",
        "source_file": "sample_data/metadatapp_kb/01_strategy/str-003_market_segmentation.md",
        "source_snippet": "CRO segment needs metadata interoperability.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["customer", "cro"],
    },
    {
        "id": "MAPP-SEG-002",
        "type": "CustomerSegment",
        "label": "Academic Preclinical Platforms",
        "description": "University or institute preclinical facilities needing structured metadata for reporting, grant compliance, and cross-lab reuse.",
        "source_document_id": "CLI-001",
        "source_file": "sample_data/metadatapp_kb/04_client_discovery/cli-001_interview_academic_platform_manager.md",
        "source_snippet": "Academic platform manager needs validation reports and structured metadata.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["customer", "academic"],
    },
    {
        "id": "MAPP-SEG-003",
        "type": "CustomerSegment",
        "label": "Pharma Translational Groups",
        "description": "Enterprise pharma groups evaluating metadata quality for AI readiness, historical control reuse, and cross-study comparability.",
        "source_document_id": "CLI-003",
        "source_file": "sample_data/metadatapp_kb/04_client_discovery/cli-003_interview_pharma_translational_group.md",
        "source_snippet": "Pharma translational group needs VCG readiness and AI-ready datasets.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["customer", "pharma"],
    },
    {
        "id": "MAPP-SEG-004",
        "type": "PartnerSegment",
        "label": "HCM Vendors",
        "description": "Home cage monitoring technology vendors that can integrate with Metadatapp via the Connector Framework to enrich their data with structured metadata.",
        "source_document_id": "CLI-004",
        "source_file": "sample_data/metadatapp_kb/04_client_discovery/cli-004_interview_hcm_vendor_partner.md",
        "source_snippet": "HCM vendor integrates with Connector Framework.",
        "confidence": "medium",
        "validation_status": "pending",
        "tags": ["partner", "hcm"],
    },
    # --- Commercial ---
    {
        "id": "MAPP-PROC-001",
        "type": "CommercialProcess",
        "label": "Pilot Program",
        "description": "Six-to-ten-week paid validation engagement measuring metadata completeness improvement and ARRIVE report assembly time.",
        "source_document_id": "COM-004",
        "source_file": "sample_data/metadatapp_kb/05_commercial/com-004_pilot_proposal_template.md",
        "source_snippet": "Six-to-ten-week validation engagement measures metadata completeness.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["commercial", "pilot"],
    },
    {
        "id": "MAPP-BIZ-001",
        "type": "BusinessModelComponent",
        "label": "Open Source Core",
        "description": "Community-oriented open-source codebase released to drive academic adoption and build a contributor ecosystem.",
        "source_document_id": "STR-005",
        "source_file": "sample_data/metadatapp_kb/01_strategy/str-005_business_model.md",
        "source_snippet": "Open Source Core supports community adoption.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["business-model", "open-source"],
    },
    {
        "id": "MAPP-BIZ-002",
        "type": "BusinessModelComponent",
        "label": "Enterprise Deployment",
        "description": "Private deployment option with support SLA, SSO, custom connectors, security controls, and compliance features.",
        "source_document_id": "COM-005",
        "source_file": "sample_data/metadatapp_kb/05_commercial/com-005_pricing_tiers.md",
        "source_snippet": "Enterprise Deployment requires Security and RBAC.",
        "confidence": "medium",
        "validation_status": "pending",
        "tags": ["business-model", "enterprise"],
    },
    {
        "id": "MAPP-BIZ-003",
        "type": "BusinessModelComponent",
        "label": "Cloud Subscription",
        "description": "Hosted SaaS tier monetizing team workflows, validation reports, FAIR exports, and standard connector packs.",
        "source_document_id": "STR-005",
        "source_file": "sample_data/metadatapp_kb/01_strategy/str-005_business_model.md",
        "source_snippet": "Cloud Subscription monetizes hosting, updates, team workflows, and validation reports.",
        "confidence": "medium",
        "validation_status": "pending",
        "tags": ["business-model", "saas"],
    },
    # --- Problems ---
    {
        "id": "MAPP-PROB-001",
        "type": "Problem",
        "label": "Fragmented Preclinical Metadata",
        "description": "Experimental metadata is fragmented across PDFs, spreadsheets, ELNs, LIMS, emails, animal facility systems, and instrument exports.",
        "source_document_id": "STR-002",
        "source_file": "sample_data/metadatapp_kb/01_strategy/str-002_problem_statement.md",
        "source_snippet": "Protocol context is fragmented across PDFs, spreadsheets, ELNs, LIMS, emails, animal facility systems, and instrument exports.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["problem", "metadata"],
    },
    {
        "id": "MAPP-PROB-002",
        "type": "Problem",
        "label": "Missing Protocol Context for HCM Data",
        "description": "Home cage monitoring data traces depend critically on cage, animal, environment, and event metadata that is often absent.",
        "source_document_id": "STR-002",
        "source_file": "sample_data/metadatapp_kb/01_strategy/str-002_problem_statement.md",
        "source_snippet": "HCM data are especially sensitive to missing context because continuous activity traces depend on cage, animal, environment, and event metadata.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["problem", "hcm"],
    },
    # --- Risks ---
    {
        "id": "MAPP-RISK-001",
        "type": "Risk",
        "label": "Keycloak Cloud Cost Risk",
        "description": "Running Keycloak continuously on JVM would significantly increase cloud costs due to idle resource usage.",
        "source_document_id": "MTG-OCT-2025",
        "source_file": "sample_data/metadatapp_kb/00_ALL_meeting_notes.txt",
        "source_snippet": "Concerns about running Keycloak continuously on JVM increasing cloud costs.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["risk", "infrastructure"],
    },
    {
        "id": "MAPP-RISK-002",
        "type": "Risk",
        "label": "Scope Creep Risk",
        "description": "Platform risks over-expanding if it tries to cover all preclinical domains too early before the HCM wedge is validated.",
        "source_document_id": "STR-008",
        "source_file": "sample_data/metadatapp_kb/01_strategy/str-008_risk_register.md",
        "source_snippet": "Scope creep is a major risk if the platform tries to cover all preclinical domains too early.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["risk", "strategy"],
    },
    {
        "id": "MAPP-RISK-003",
        "type": "Risk",
        "label": "Adoption Risk",
        "description": "Scientists may perceive metadata capture as extra administrative burden, blocking organic adoption.",
        "source_document_id": "STR-008",
        "source_file": "sample_data/metadatapp_kb/01_strategy/str-008_risk_register.md",
        "source_snippet": "Adoption risk is high if scientists perceive metadata capture as extra administrative work.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["risk", "adoption"],
    },
    {
        "id": "MAPP-RISK-004",
        "type": "Risk",
        "label": "VCG Overclaiming Risk",
        "description": "Risk that VCG readiness language overclaims what metadata can prove, threatening scientific credibility.",
        "source_document_id": "STR-008",
        "source_file": "sample_data/metadatapp_kb/01_strategy/str-008_risk_register.md",
        "source_snippet": "VCG language overclaiming threatens scientific credibility.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["risk", "scientific-credibility"],
    },
    # --- Assumptions ---
    {
        "id": "MAPP-ASSUMP-001",
        "type": "Assumption",
        "label": "CROs will pay for metadata interoperability",
        "description": "Preclinical CROs will pay for Metadatapp if it demonstrably reduces duplicated data entry and improves study report assembly.",
        "source_document_id": "STR-003",
        "source_file": "sample_data/metadatapp_kb/01_strategy/str-003_market_segmentation.md",
        "source_snippet": "CROs will pay for integration if it reduces duplicated data entry.",
        "confidence": "medium",
        "validation_status": "pending",
        "tags": ["assumption", "pricing"],
    },
    {
        "id": "MAPP-ASSUMP-002",
        "type": "Assumption",
        "label": "Better metadata enables reduction in avoidable experiments",
        "description": "Improved metadata infrastructure will support 3Rs decisions by enabling better historical data reuse, reducing unnecessary animal experiments.",
        "source_document_id": "STR-001",
        "source_file": "sample_data/metadatapp_kb/01_strategy/str-001_vision_and_mission.md",
        "source_snippet": "Better metadata can reduce avoidable duplication and improve interpretation.",
        "confidence": "medium",
        "validation_status": "pending",
        "tags": ["assumption", "3rs", "ethical"],
    },
    {
        "id": "MAPP-ASSUMP-003",
        "type": "Assumption",
        "label": "Pharma needs metadata for AI-readiness",
        "description": "Pharma translational teams will sponsor pilots when metadata quality directly affects their AI-ready dataset requirements.",
        "source_document_id": "CLI-003",
        "source_file": "sample_data/metadatapp_kb/04_client_discovery/cli-003_interview_pharma_translational_group.md",
        "source_snippet": "Pharma needs traceable metadata for AI-ready research datasets.",
        "confidence": "medium",
        "validation_status": "pending",
        "tags": ["assumption", "pharma", "ai-readiness"],
    },
    # --- Metrics ---
    {
        "id": "MAPP-METRIC-001",
        "type": "Metric",
        "label": "Metadata Completeness Score",
        "description": "Quantitative score measuring the percentage of required metadata fields populated for a given experiment.",
        "source_document_id": "COM-004",
        "source_file": "sample_data/metadatapp_kb/05_commercial/com-004_pilot_proposal_template.md",
        "source_snippet": "Pilot Program measures Metadata Completeness.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["metric", "pilot"],
    },
    {
        "id": "MAPP-METRIC-002",
        "type": "Metric",
        "label": "ARRIVE Report Assembly Time",
        "description": "Time required to compile an ARRIVE-compliant report from experiment metadata — a key pilot success metric for CROs.",
        "source_document_id": "CLI-002",
        "source_file": "sample_data/metadatapp_kb/04_client_discovery/cli-002_interview_cro_project_lead.md",
        "source_snippet": "CRO Pilot measures Report Assembly Time.",
        "confidence": "medium",
        "validation_status": "pending",
        "tags": ["metric", "cro"],
    },
    # --- Milestones ---
    {
        "id": "MAPP-MILESTONE-001",
        "type": "Milestone",
        "label": "GCloud MVP Deployment",
        "description": "Deploy current Metadatapp version on Google Cloud with new lightweight authentication replacing Keycloak.",
        "source_document_id": "MTG-OCT-2025",
        "source_file": "sample_data/metadatapp_kb/00_ALL_meeting_notes.txt",
        "source_snippet": "Milestones 1: Deploiement Gcloud de la version actuelle avec nouvelle authentification.",
        "confidence": "high",
        "validation_status": "pending",
        "tags": ["milestone", "deployment"],
        "deadline": "2025-11-30",
    },
    {
        "id": "MAPP-MILESTONE-002",
        "type": "Milestone",
        "label": "Connected Apps Integration",
        "description": "Launch integrations with ElabFTW, SoftMouse, ORCID, ROR, OSF, and Fair3R as connected app connectors.",
        "source_document_id": "MTG-OCT-2025",
        "source_file": "sample_data/metadatapp_kb/00_ALL_meeting_notes.txt",
        "source_snippet": "Milestones 2: Connected Apps — ElabFTW, SoftMouse, Fair3R, ORCID, ROR, OSF.",
        "confidence": "medium",
        "validation_status": "pending",
        "tags": ["milestone", "integration"],
    },
]

_METADATAPP_RELATION_TEMPLATES: list[dict[str, Any]] = [
    # --- Core product edges from node/edge registry ---
    {
        "id": "MAPP-REL-001",
        "subject_id": "MAPP-PROJ-001",
        "subject_type": "StartupProject",
        "predicate": "HAS_INITIAL_WEDGE",
        "object_id": "MAPP-UC-001",
        "object_type": "UseCase",
        "source_document_id": "STR-010",
        "source_file": "sample_data/metadatapp_kb/01_strategy/str-010_positioning_statement.md",
        "source_snippet": "Metadatapp has_initial_wedge Home Cage Monitoring.",
        "confidence": "high",
        "validation_status": "pending",
    },
    {
        "id": "MAPP-REL-002",
        "subject_id": "MAPP-PROJ-001",
        "subject_type": "StartupProject",
        "predicate": "SUPPORTS",
        "object_id": "MAPP-CONC-001",
        "object_type": "Concept",
        "source_document_id": "STR-001",
        "source_file": "sample_data/metadatapp_kb/01_strategy/str-001_vision_and_mission.md",
        "source_snippet": "Metadatapp supports FAIRRR.",
        "confidence": "high",
        "validation_status": "pending",
    },
    {
        "id": "MAPP-REL-003",
        "subject_id": "MAPP-PROJ-001",
        "subject_type": "StartupProject",
        "predicate": "EXPORTS",
        "object_id": "MAPP-EXP-001",
        "object_type": "ExportFormat",
        "source_document_id": "PRD-006",
        "source_file": "sample_data/metadatapp_kb/02_product/prd-006_import_export_specification.md",
        "source_snippet": "Metadatapp exports JSON-LD format.",
        "confidence": "high",
        "validation_status": "pending",
    },
    {
        "id": "MAPP-REL-004",
        "subject_id": "MAPP-PROJ-001",
        "subject_type": "StartupProject",
        "predicate": "EXPORTS",
        "object_id": "MAPP-EXP-002",
        "object_type": "ExportFormat",
        "source_document_id": "PRD-006",
        "source_file": "sample_data/metadatapp_kb/02_product/prd-006_import_export_specification.md",
        "source_snippet": "Metadatapp exports RO-Crate format.",
        "confidence": "high",
        "validation_status": "pending",
    },
    {
        "id": "MAPP-REL-005",
        "subject_id": "MAPP-PROJ-001",
        "subject_type": "StartupProject",
        "predicate": "GENERATES",
        "object_id": "MAPP-EXP-003",
        "object_type": "ExportFormat",
        "source_document_id": "PRD-009",
        "source_file": "sample_data/metadatapp_kb/02_product/prd-009_arrive_export.md",
        "source_snippet": "Metadatapp generates ARRIVE export.",
        "confidence": "high",
        "validation_status": "pending",
    },
    {
        "id": "MAPP-REL-006",
        "subject_id": "MAPP-MOD-001",
        "subject_type": "ProductModule",
        "predicate": "USES",
        "object_id": "MAPP-TECH-001",
        "object_type": "TechnicalCapability",
        "source_document_id": "TECH-005",
        "source_file": "sample_data/metadatapp_kb/03_technical/tech-005_shacl_validation_strategy.md",
        "source_snippet": "Validation Report uses SHACL Validation.",
        "confidence": "high",
        "validation_status": "pending",
    },
    {
        "id": "MAPP-REL-007",
        "subject_id": "MAPP-TECH-002",
        "subject_type": "TechnicalCapability",
        "predicate": "SUPPORTS",
        "object_id": "MAPP-EXP-001",
        "object_type": "ExportFormat",
        "source_document_id": "TECH-006",
        "source_file": "sample_data/metadatapp_kb/03_technical/tech-006_ontology_layer.md",
        "source_snippet": "Ontology Layer supports JSON-LD export.",
        "confidence": "high",
        "validation_status": "pending",
    },
    {
        "id": "MAPP-REL-008",
        "subject_id": "MAPP-SEG-001",
        "subject_type": "CustomerSegment",
        "predicate": "BUYS_FOR",
        "object_id": "MAPP-EXP-003",
        "object_type": "ExportFormat",
        "source_document_id": "CLI-002",
        "source_file": "sample_data/metadatapp_kb/04_client_discovery/cli-002_interview_cro_project_lead.md",
        "source_snippet": "CRO buys for ARRIVE export to reduce report assembly time.",
        "confidence": "medium",
        "validation_status": "pending",
    },
    {
        "id": "MAPP-REL-009",
        "subject_id": "MAPP-SEG-002",
        "subject_type": "CustomerSegment",
        "predicate": "NEEDS",
        "object_id": "MAPP-MOD-001",
        "object_type": "ProductModule",
        "source_document_id": "CLI-001",
        "source_file": "sample_data/metadatapp_kb/04_client_discovery/cli-001_interview_academic_platform_manager.md",
        "source_snippet": "Academic platform needs Validation Report.",
        "confidence": "high",
        "validation_status": "pending",
    },
    {
        "id": "MAPP-REL-010",
        "subject_id": "MAPP-SEG-003",
        "subject_type": "CustomerSegment",
        "predicate": "NEEDS",
        "object_id": "MAPP-MOD-002",
        "object_type": "ProductModule",
        "source_document_id": "CLI-003",
        "source_file": "sample_data/metadatapp_kb/04_client_discovery/cli-003_interview_pharma_translational_group.md",
        "source_snippet": "Pharma Translational Group needs VCG Readiness Module.",
        "confidence": "medium",
        "validation_status": "pending",
    },
    {
        "id": "MAPP-REL-011",
        "subject_id": "MAPP-SEG-004",
        "subject_type": "PartnerSegment",
        "predicate": "INTEGRATES_WITH",
        "object_id": "MAPP-TECH-003",
        "object_type": "TechnicalCapability",
        "source_document_id": "CLI-004",
        "source_file": "sample_data/metadatapp_kb/04_client_discovery/cli-004_interview_hcm_vendor_partner.md",
        "source_snippet": "HCM Vendor integrates with Connector Framework.",
        "confidence": "medium",
        "validation_status": "pending",
    },
    {
        "id": "MAPP-REL-012",
        "subject_id": "MAPP-FEAT-001",
        "subject_type": "ProductFeature",
        "predicate": "REQUIRES",
        "object_id": "MAPP-CONC-002",
        "object_type": "Concept",
        "source_document_id": "PRD-007",
        "source_file": "sample_data/metadatapp_kb/02_product/prd-007_ai_assistant_boundaries.md",
        "source_snippet": "AI Assistant requires Human Review.",
        "confidence": "high",
        "validation_status": "pending",
    },
    {
        "id": "MAPP-REL-013",
        "subject_id": "MAPP-PROC-001",
        "subject_type": "CommercialProcess",
        "predicate": "MEASURES",
        "object_id": "MAPP-METRIC-001",
        "object_type": "Metric",
        "source_document_id": "COM-004",
        "source_file": "sample_data/metadatapp_kb/05_commercial/com-004_pilot_proposal_template.md",
        "source_snippet": "Pilot Program measures Metadata Completeness.",
        "confidence": "high",
        "validation_status": "pending",
    },
    {
        "id": "MAPP-REL-014",
        "subject_id": "MAPP-BIZ-001",
        "subject_type": "BusinessModelComponent",
        "predicate": "SUPPORTS",
        "object_id": "MAPP-CONC-003",
        "object_type": "Concept",
        "source_document_id": "STR-005",
        "source_file": "sample_data/metadatapp_kb/01_strategy/str-005_business_model.md",
        "source_snippet": "Open Source Core supports Community Adoption.",
        "confidence": "medium",
        "validation_status": "pending",
    },
    {
        "id": "MAPP-REL-015",
        "subject_id": "MAPP-BIZ-002",
        "subject_type": "BusinessModelComponent",
        "predicate": "REQUIRES",
        "object_id": "MAPP-TECH-004",
        "object_type": "TechnicalCapability",
        "source_document_id": "COM-005",
        "source_file": "sample_data/metadatapp_kb/05_commercial/com-005_pricing_tiers.md",
        "source_snippet": "Enterprise Deployment requires Security and RBAC.",
        "confidence": "medium",
        "validation_status": "pending",
    },
    # --- Strategy and problem relations ---
    {
        "id": "MAPP-REL-016",
        "subject_id": "MAPP-PROJ-001",
        "subject_type": "StartupProject",
        "predicate": "ADDRESSES",
        "object_id": "MAPP-PROB-001",
        "object_type": "Problem",
        "source_document_id": "STR-002",
        "source_file": "sample_data/metadatapp_kb/01_strategy/str-002_problem_statement.md",
        "source_snippet": "Metadatapp addresses fragmented preclinical metadata.",
        "confidence": "high",
        "validation_status": "pending",
    },
    {
        "id": "MAPP-REL-017",
        "subject_id": "MAPP-PROJ-001",
        "subject_type": "StartupProject",
        "predicate": "IMPLEMENTS",
        "object_id": "MAPP-STAND-001",
        "object_type": "Standard",
        "source_document_id": "STR-001",
        "source_file": "sample_data/metadatapp_kb/01_strategy/str-001_vision_and_mission.md",
        "source_snippet": "Metadatapp implements FAIR Principles.",
        "confidence": "high",
        "validation_status": "pending",
    },
    {
        "id": "MAPP-REL-018",
        "subject_id": "MAPP-UC-001",
        "subject_type": "UseCase",
        "predicate": "REQUIRES",
        "object_id": "MAPP-TECH-002",
        "object_type": "TechnicalCapability",
        "source_document_id": "KG-003",
        "source_file": "sample_data/metadatapp_kb/08_knowledge_graph/kg-003_example_triples.md",
        "source_snippet": "Home Cage Monitoring requires Protocol Context via Ontology Layer.",
        "confidence": "high",
        "validation_status": "pending",
    },
    # --- People and team relations ---
    {
        "id": "MAPP-REL-019",
        "subject_id": "MAPP-PERSON-001",
        "subject_type": "Person",
        "predicate": "FOUNDED",
        "object_id": "MAPP-PROJ-001",
        "object_type": "StartupProject",
        "source_document_id": "MTG-OCT-2025",
        "source_file": "sample_data/metadatapp_kb/00_ALL_meeting_notes.txt",
        "source_snippet": "Damien HUZARD — co-founder leading product strategy and pitch.",
        "confidence": "high",
        "validation_status": "pending",
    },
    {
        "id": "MAPP-REL-020",
        "subject_id": "MAPP-PERSON-002",
        "subject_type": "Person",
        "predicate": "LEADS_TECHNICAL_DEVELOPMENT_FOR",
        "object_id": "MAPP-PROJ-001",
        "object_type": "StartupProject",
        "source_document_id": "MTG-OCT-2025",
        "source_file": "sample_data/metadatapp_kb/00_ALL_meeting_notes.txt",
        "source_snippet": "Rakesh Beedasy: Prepare Terraform scripts and CI/CD pipeline.",
        "confidence": "high",
        "validation_status": "pending",
    },
    # --- Decision relations ---
    {
        "id": "MAPP-REL-021",
        "subject_id": "MAPP-DEC-001",
        "subject_type": "Decision",
        "predicate": "MITIGATES",
        "object_id": "MAPP-RISK-001",
        "object_type": "Risk",
        "source_document_id": "MTG-OCT-2025",
        "source_file": "sample_data/metadatapp_kb/00_ALL_meeting_notes.txt",
        "source_snippet": "Decision to drop Keycloak mitigates cloud cost risk.",
        "confidence": "high",
        "validation_status": "pending",
    },
    {
        "id": "MAPP-REL-022",
        "subject_id": "MAPP-DEC-003",
        "subject_type": "Decision",
        "predicate": "MITIGATES",
        "object_id": "MAPP-RISK-002",
        "object_type": "Risk",
        "source_document_id": "STR-008",
        "source_file": "sample_data/metadatapp_kb/01_strategy/str-008_risk_register.md",
        "source_snippet": "HCM wedge strategy mitigates scope creep risk.",
        "confidence": "high",
        "validation_status": "pending",
    },
    # --- Connector Framework dependencies ---
    {
        "id": "MAPP-REL-023",
        "subject_id": "MAPP-TECH-003",
        "subject_type": "TechnicalCapability",
        "predicate": "INTEGRATES_WITH",
        "object_id": "MAPP-TECH-007",
        "object_type": "Technology",
        "source_document_id": "MTG-OCT-2025",
        "source_file": "sample_data/metadatapp_kb/00_ALL_meeting_notes.txt",
        "source_snippet": "Connector Framework integrates ElabFTW as a connected app.",
        "confidence": "high",
        "validation_status": "pending",
    },
    {
        "id": "MAPP-REL-024",
        "subject_id": "MAPP-TECH-003",
        "subject_type": "TechnicalCapability",
        "predicate": "INTEGRATES_WITH",
        "object_id": "MAPP-TECH-008",
        "object_type": "Technology",
        "source_document_id": "MTG-OCT-2025",
        "source_file": "sample_data/metadatapp_kb/00_ALL_meeting_notes.txt",
        "source_snippet": "Connector Framework integrates SoftMouse for animal cohort metadata.",
        "confidence": "high",
        "validation_status": "pending",
    },
    {
        "id": "MAPP-REL-025",
        "subject_id": "MAPP-TECH-003",
        "subject_type": "TechnicalCapability",
        "predicate": "INTEGRATES_WITH",
        "object_id": "MAPP-TECH-010",
        "object_type": "Technology",
        "source_document_id": "MTG-OCT-2025",
        "source_file": "sample_data/metadatapp_kb/00_ALL_meeting_notes.txt",
        "source_snippet": "Metadatapp syncs with Fair3R repository applying FAIR metadata schema.",
        "confidence": "high",
        "validation_status": "pending",
    },
    # --- Milestone relations ---
    {
        "id": "MAPP-REL-026",
        "subject_id": "MAPP-MILESTONE-001",
        "subject_type": "Milestone",
        "predicate": "DEPENDS_ON",
        "object_id": "MAPP-TECH-005",
        "object_type": "Technology",
        "source_document_id": "MTG-OCT-2025",
        "source_file": "sample_data/metadatapp_kb/00_ALL_meeting_notes.txt",
        "source_snippet": "GCloud MVP deployment uses Google Cloud Run.",
        "confidence": "high",
        "validation_status": "pending",
    },
    {
        "id": "MAPP-REL-027",
        "subject_id": "MAPP-MILESTONE-001",
        "subject_type": "Milestone",
        "predicate": "DEPENDS_ON",
        "object_id": "MAPP-TECH-006",
        "object_type": "Technology",
        "source_document_id": "MTG-OCT-2025",
        "source_file": "sample_data/metadatapp_kb/00_ALL_meeting_notes.txt",
        "source_snippet": "Terraform scripts provision the deployment infrastructure.",
        "confidence": "high",
        "validation_status": "pending",
    },
    # --- Assumption supports ---
    {
        "id": "MAPP-REL-028",
        "subject_id": "MAPP-ASSUMP-002",
        "subject_type": "Assumption",
        "predicate": "SUPPORTS",
        "object_id": "MAPP-CONC-001",
        "object_type": "Concept",
        "source_document_id": "STR-001",
        "source_file": "sample_data/metadatapp_kb/01_strategy/str-001_vision_and_mission.md",
        "source_snippet": "Better metadata reduces avoidable duplication, supporting FAIRRR mission.",
        "confidence": "medium",
        "validation_status": "pending",
    },
    {
        "id": "MAPP-REL-029",
        "subject_id": "MAPP-PROC-001",
        "subject_type": "CommercialProcess",
        "predicate": "MEASURES",
        "object_id": "MAPP-METRIC-002",
        "object_type": "Metric",
        "source_document_id": "CLI-002",
        "source_file": "sample_data/metadatapp_kb/04_client_discovery/cli-002_interview_cro_project_lead.md",
        "source_snippet": "CRO Pilot measures Report Assembly Time.",
        "confidence": "medium",
        "validation_status": "pending",
    },
    {
        "id": "MAPP-REL-030",
        "subject_id": "MAPP-PROJ-001",
        "subject_type": "StartupProject",
        "predicate": "HAS_BUSINESS_MODEL",
        "object_id": "MAPP-BIZ-001",
        "object_type": "BusinessModelComponent",
        "source_document_id": "STR-005",
        "source_file": "sample_data/metadatapp_kb/01_strategy/str-005_business_model.md",
        "source_snippet": "Metadatapp business model includes Open Source Core.",
        "confidence": "high",
        "validation_status": "pending",
    },
]


def seed_metadatapp_candidates(overwrite: bool = False) -> tuple[Path, Path]:
    return _write_candidates(_METADATAPP_ENTITY_TEMPLATES, _METADATAPP_RELATION_TEMPLATES, overwrite=overwrite)
